import { Parser } from "json2csv";
import PDFDocument from "pdfkit";
import { Contract, Task, ComplianceResult } from "../models";

class ReportService {
  /**
   * Generate CSV export of contracts
   */
  async generateContractsCSV(organizationId: string): Promise<string> {
    const contracts = await Contract.find({ organizationId })
      .populate("uploadedBy", "email")
      .populate("assignedTo", "email")
      .lean();

    const csvData = contracts.map((contract: any) => ({
      Title: contract.title,
      Vendor: contract.vendor || "",
      Status: contract.status,
      RiskScore: contract.riskScore || "",
      AssignedTo: contract.assignedTo?.email || "",
      UploadedBy: contract.uploadedBy?.email,
      Tags: contract.tags?.join(", ") || "",
      CreatedAt: new Date(contract.createdAt).toISOString(),
    }));

    const parser = new Parser({
      fields: [
        "Title",
        "Vendor",
        "Status",
        "RiskScore",
        "AssignedTo",
        "UploadedBy",
        "Tags",
        "CreatedAt",
      ],
    });

    return parser.parse(csvData);
  }

  /**
   * Generate tasks CSV export
   */
  async generateTasksCSV(organizationId: string): Promise<string> {
    const tasks = await Task.find({ organizationId })
      .populate("contractId", "title")
      .populate("assignedTo", "email")
      .populate("createdBy", "email")
      .lean();

    const csvData = tasks.map((task: any) => ({
      Title: task.title,
      Type: task.type,
      Contract: task.contractId?.title || "",
      DueDate: new Date(task.dueDate).toISOString(),
      Status: task.status,
      Priority: task.priority,
      AssignedTo: task.assignedTo?.email || "",
      AutoGenerated: task.autoGenerated ? "Yes" : "No",
      CreatedAt: new Date(task.createdAt).toISOString(),
    }));

    const parser = new Parser({
      fields: [
        "Title",
        "Type",
        "Contract",
        "DueDate",
        "Status",
        "Priority",
        "AssignedTo",
        "AutoGenerated",
        "CreatedAt",
      ],
    });

    return parser.parse(csvData);
  }

  /**
   * Generate status report PDF
   */
  async generateStatusReportPDF(organizationId: string): Promise<Buffer> {
    const contracts = await Contract.find({ organizationId }).lean();

    const statusCounts = {
      Pending: contracts.filter((c: any) => c.status === "Pending").length,
      Reviewed: contracts.filter((c: any) => c.status === "Reviewed").length,
      Approved: contracts.filter((c: any) => c.status === "Approved").length,
      Rejected: contracts.filter((c: any) => c.status === "Rejected").length,
      Expired: contracts.filter((c: any) => c.status === "Expired").length,
    };

    return this.createPDFReport("Contract Status Report", [
      { label: "Total Contracts", value: contracts.length.toString() },
      { label: "Pending", value: statusCounts.Pending.toString() },
      { label: "Reviewed", value: statusCounts.Reviewed.toString() },
      { label: "Approved", value: statusCounts.Approved.toString() },
      { label: "Rejected", value: statusCounts.Rejected.toString() },
      { label: "Expired", value: statusCounts.Expired.toString() },
    ]);
  }

  /**
   * Generate risk report PDF
   */
  async generateRiskReportPDF(organizationId: string): Promise<Buffer> {
    const contracts = await Contract.find({
      organizationId,
      riskScore: { $exists: true },
    })
      .sort({ riskScore: -1 })
      .limit(20)
      .lean();

    const highRisk = contracts.filter((c: any) => c.riskScore >= 70).length;
    const mediumRisk = contracts.filter(
      (c: any) => c.riskScore >= 40 && c.riskScore < 70
    ).length;
    const lowRisk = contracts.filter((c: any) => c.riskScore < 40).length;

    const data = [
      { label: "Total Analyzed", value: contracts.length.toString() },
      { label: "High Risk (70+)", value: highRisk.toString() },
      { label: "Medium Risk (40-69)", value: mediumRisk.toString() },
      { label: "Low Risk (0-39)", value: lowRisk.toString() },
    ];

    // Add top 5 high-risk contracts
    const topRisks = contracts.slice(0, 5).map((c: any) => ({
      label: c.title,
      value: `Score: ${c.riskScore}`,
    }));

    return this.createPDFReport("Risk Analysis Report", [...data, ...topRisks]);
  }

  /**
   * Generate compliance report PDF
   */
  async generateComplianceReportPDF(organizationId: string): Promise<Buffer> {
    const results = await ComplianceResult.find({ organizationId }).lean();

    const passed = results.filter((r: any) => r.passed).length;
    const failed = results.length - passed;
    const averageScore =
      results.length > 0
        ? results.reduce((sum: number, r: any) => sum + r.score, 0) /
          results.length
        : 0;

    return this.createPDFReport("Compliance Report", [
      { label: "Total Contracts Checked", value: results.length.toString() },
      { label: "Passed", value: passed.toString() },
      { label: "Failed", value: failed.toString() },
      { label: "Average Score", value: `${Math.round(averageScore)}/100` },
    ]);
  }

  /**
   * Helper to create PDF report
   */
  private createPDFReport(
    title: string,
    data: Array<{ label: string; value: string }>
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument();
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc.fontSize(24).font("Helvetica-Bold").text(title, { align: "center" });

      doc.moveDown();
      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });

      doc.moveDown(2);

      // Data
      data.forEach((item) => {
        doc
          .fontSize(12)
          .font("Helvetica-Bold")
          .text(`${item.label}:`, { continued: true })
          .font("Helvetica")
          .text(` ${item.value}`);
        doc.moveDown(0.5);
      });

      // Footer
      doc.moveDown(2);
      doc
        .fontSize(8)
        .fillColor("gray")
        .text("Generated by Clause-IQ", { align: "center" });

      doc.end();
    });
  }
}

export default new ReportService();
