import { Response } from "express";
import { Contract } from "../models";
import Task from "../models/Task";
import { AuthRequest } from "../types";
import { AppError, asyncHandler } from "../middleware/errorHandler";
import { sendSuccess } from "../utils/response";

// Get all tasks for organization
export const getTasks = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const user = req.user!;
    const {
      status,
      priority,
      assignedTo,
      contractId,
      type,
      page = 1,
      limit = 20,
    } = req.query;

    const filter: any = { organizationId: user.organizationId };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;
    if (assignedTo) filter.assignedTo = assignedTo;
    if (contractId) filter.contractId = contractId;
    if (type) filter.type = type;

    const skip = (Number(page) - 1) * Number(limit);

    const [tasks, total] = await Promise.all([
      Task.find(filter)
        .populate("assignedTo", "email firstName lastName")
        .populate("contractId", "title vendor")
        .populate("createdBy", "email")
        .sort({ dueDate: 1 })
        .skip(skip)
        .limit(Number(limit)),
      Task.countDocuments(filter),
    ]);

    sendSuccess(res, {
      tasks,
      pagination: {
        total,
        page: Number(page),
        limit: Number(limit),
        pages: Math.ceil(total / Number(limit)),
      },
    });
  }
);

// Get single task
export const getTaskById = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const user = req.user!;
    const { taskId } = req.params;

    const task = await Task.findOne({
      _id: taskId,
      organizationId: user.organizationId,
    })
      .populate("assignedTo", "email firstName lastName")
      .populate("contractId", "title vendor")
      .populate("createdBy", "email")
      .populate("completedBy", "email");

    if (!task) {
      throw new AppError("Task not found", 404);
    }

    sendSuccess(res, { task });
  }
);

// Create task
export const createTask = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const user = req.user!;
    const {
      contractId,
      type,
      title,
      description,
      dueDate,
      assignedTo,
      priority,
    } = req.body;

    // Validate contract exists and belongs to organization
    const contract = await Contract.findOne({
      _id: contractId,
      organizationId: user.organizationId,
    });

    if (!contract) {
      throw new AppError("Contract not found", 404);
    }

    // Validate assignedTo user if provided
    if (assignedTo) {
      const { User } = await import("../models");
      const assignedUser = await User.findOne({
        _id: assignedTo,
        organizationId: user.organizationId,
      });
      if (!assignedUser) {
        throw new AppError("Assigned user not found in organization", 404);
      }
    }

    const task = await Task.create({
      contractId,
      organizationId: user.organizationId,
      type: type || "custom",
      title,
      description,
      dueDate,
      assignedTo,
      priority: priority || "medium",
      status: "pending",
      autoGenerated: false,
      createdBy: user._id,
    });

    const populatedTask = await Task.findById(task._id)
      .populate("assignedTo", "email firstName lastName")
      .populate("contractId", "title vendor")
      .populate("createdBy", "email");

    sendSuccess(res, { task: populatedTask }, "Task created successfully", 201);
  }
);

// Update task
export const updateTask = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const user = req.user!;
    const { taskId } = req.params;
    const updates = req.body;

    const task = await Task.findOne({
      _id: taskId,
      organizationId: user.organizationId,
    });

    if (!task) {
      throw new AppError("Task not found", 404);
    }

    // Validate assignedTo user if being updated
    if (updates.assignedTo) {
      const { User } = await import("../models");
      const assignedUser = await User.findOne({
        _id: updates.assignedTo,
        organizationId: user.organizationId,
      });
      if (!assignedUser) {
        throw new AppError("Assigned user not found in organization", 404);
      }
    }

    // Handle status change to completed
    if (updates.status === "completed" && task.status !== "completed") {
      updates.completedAt = new Date();
      updates.completedBy = user._id;
    }

    // Allowed fields for update
    const allowedUpdates = [
      "title",
      "description",
      "dueDate",
      "assignedTo",
      "status",
      "priority",
      "type",
    ];

    allowedUpdates.forEach((field) => {
      if (updates[field] !== undefined) {
        (task as any)[field] = updates[field];
      }
    });

    // Apply completedAt and completedBy if set
    if (updates.completedAt) task.completedAt = updates.completedAt;
    if (updates.completedBy) task.completedBy = updates.completedBy;

    await task.save();

    const updatedTask = await Task.findById(task._id)
      .populate("assignedTo", "email firstName lastName")
      .populate("contractId", "title vendor")
      .populate("createdBy", "email")
      .populate("completedBy", "email");

    sendSuccess(res, { task: updatedTask }, "Task updated successfully");
  }
);

// Delete task
export const deleteTask = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const user = req.user!;
    const { taskId } = req.params;

    const task = await Task.findOne({
      _id: taskId,
      organizationId: user.organizationId,
    });

    if (!task) {
      throw new AppError("Task not found", 404);
    }

    await task.deleteOne();

    sendSuccess(res, null, "Task deleted successfully");
  }
);

// Get upcoming tasks (dashboard widget)
export const getUpcomingTasks = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const user = req.user!;
    const { days = 30 } = req.query;

    const today = new Date();
    const futureDate = new Date();
    futureDate.setDate(today.getDate() + Number(days));

    const tasks = await Task.find({
      organizationId: user.organizationId,
      status: { $in: ["pending", "in_progress"] },
      dueDate: { $gte: today, $lte: futureDate },
    })
      .populate("assignedTo", "email firstName lastName")
      .populate("contractId", "title vendor")
      .sort({ dueDate: 1 })
      .limit(10);

    sendSuccess(res, { tasks, days: Number(days) });
  }
);

// Get my assigned tasks
export const getMyTasks = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const user = req.user!;
    const { status, page = 1, limit = 20 } = req.query;

    const filter: any = {
      organizationId: user.organizationId,
      assignedTo: user._id,
    };

    if (status) filter.status = status;

    const skip = (Number(page) - 1) * Number(limit);

    const [tasks, total] = await Promise.all([
      Task.find(filter)
        .populate("contractId", "title vendor")
        .populate("createdBy", "email")
        .sort({ dueDate: 1 })
        .skip(skip)
        .limit(Number(limit)),
      Task.countDocuments(filter),
    ]);

    sendSuccess(res, {
      tasks,
      pagination: {
        total,
        page: Number(page),
        limit: Number(limit),
        pages: Math.ceil(total / Number(limit)),
      },
    });
  }
);
